
props Object {
  "dispatch": [Function anonymous],
  "eventDetails": Array [
    Object {
      "created": 1456184674000,
      "description": "<p>Location: Booze Brothers. The tasting room has a great vibe. This is our quarterly SDJS hangout we host it at a local bar around SanDiego county. It's open to all community members, 21 and up. It's is an informal hangout so feel free to stop by, bring your laptop, have a cold beverage, and chat about problems or solutions you're dealing with using JavaScript.</p> <p>Please respect our Code of Conduct</p> <p>We welcome people of all backgrounds and skill levels. In keeping with the sandiego.js spirit, please be friendly, welcoming, and respectful.</p> <p>Please be respectful of others and respect our code of conduct (<a href=\"http://sandiegojs.org/code-of-conduct.html\" class=\"linkified\">http://sandiegojs.org/code-of-conduct.html</a>).</p> ",
      "duration": 7200000,
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "how_to_find_us": "Park on the street or in the lot to the east of Booze Brothers",
      "id": "fqgtqlyxcbrb",
      "link": "https://www.meetup.com/sandiegojs/events/246082820/",
      "local_date": "2018-01-27",
      "local_time": "16:00",
      "name": "SDJS Social Hour",
      "status": "upcoming",
      "time": 1517097600000,
      "updated": 1516075455000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "2545 Progress St Ste D",
        "city": "Vista",
        "country": "US",
        "id": 19364922,
        "lat": 33.14801025390625,
        "localized_country_name": "USA",
        "lon": -117.21770477294922,
        "name": "Booze Brothers",
        "repinned": false,
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 31,
    },
    Object {
      "created": 1499106128000,
      "description": "<p>Speakers:<br/>TBD</p> <p>San Diego JavaScript meets the first Tuesday of each month, at Zeeto Downtown. This event will take place in Zeeto's Questionable Exchange on the first floor. We typically have a series of short talks and then hang out and socialize.</p> <p>@ 7:30 pm you can park in any available Zeeto parking spots (see the map).</p> <p>Want to give a talk?</p> <p>We typically host four to six 5 minute lightning talks each month. We want to hear you speak and we're here to help you give a talk. Find out how to give a 5 minute talk at our next event. (<a href=\"http://sandiegojs.org/give-a-talk.html\" class=\"linkified\">http://sandiegojs.org/give-a-talk.html</a>)</p> <p>Please respect our Code of Conduct</p> <p>We welcome people of all backgrounds and skill levels. In keeping with the sandiego.js spirit, please be friendly, welcoming, and respectful.</p> <p>Please be respectful of others and respect our code of conduct (<a href=\"http://sandiegojs.org/code-of-conduct.html\" class=\"linkified\">http://sandiegojs.org/code-of-conduct.html</a>).</p> <p>Find us online</p> <p>Our website is sandiegojs.org (<a href=\"http://sandiegojs.org/\" class=\"linkified\">http://sandiegojs.org/</a>). Our IRC channel (<a href=\"http://sandiegojs.org/chat-room.html\" class=\"linkified\">http://sandiegojs.org/chat-room.html</a>) is #sandiegojs on FreeNode. We also have a Slack channel.</p> <p>Parking info</p> <p><img src=\"https://secure.meetupstatic.com/photos/event/3/d/3/3/600_444675667.jpeg\" /></p> ",
      "duration": 10800000,
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "id": "ktlwfpyxdbjb",
      "link": "https://www.meetup.com/sandiegojs/events/246651133/",
      "local_date": "2018-02-06",
      "local_time": "19:30",
      "name": "San Diego JS Monthly Meeting",
      "rsvp_limit": 150,
      "status": "upcoming",
      "time": 1517974200000,
      "updated": 1516139730000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "925 B St.",
        "city": "San Diego",
        "country": "us",
        "id": 24306491,
        "lat": 32.71753692626953,
        "localized_country_name": "USA",
        "lon": -117.1558837890625,
        "name": "Zeeto",
        "repinned": false,
        "state": "CA",
        "zip": "92101",
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 35,
    },
    Object {
      "created": 1503534284000,
      "description": "<p><b>Game Dev Night</b> runs <b>e</b><b>very 2nd Tuesday</b> of the month. We're here to talk shop about all Game Dev topics, especially those revolving around JS and HTML5 games. Normally we'll have a presentation or two, then you'll be able to collaborate and learn from each other.</p> <p>We're open to everyone coming in, beginners, seniors, artists, and developers. Anyone looking to make, work, and play games.</p> <p>


<b>PARKING</b></p> <p><br/>Unfortunately we cannot help with parking. Horton Plaza is within two blocks and has one hour of parking for free, then charges $8 an hour.</p> <p><b><br/></b></p> <p><b>GETTING IN</b></p> <p>Walk up the to entrance of the building that faces the Horton Plaza mall. You may have to knock on the glass doors to be let in. Once you're in the lobby, ask the front desk attendant to be let up to the 11th floor for the Origin Code Academy meetup.</p> <p><b><br/></b></p> <p><b>Please respect our Code of Conduct </b></p> <p>We welcome people of all backgrounds and skill levels.  In keeping with the sandiego.js spirit, please be friendly, welcoming, and respectful.</p> <p>Please be respectful of others and respect our <a href=\"http://sandiegojs.org/code-of-conduct.html\">code of conduct</a>.</p> ",
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "id": "dvzxqnyxdbrb",
      "link": "https://www.meetup.com/sandiegojs/events/246652798/",
      "local_date": "2018-02-13",
      "local_time": "19:00",
      "name": "Game Dev Night",
      "rsvp_limit": 100,
      "status": "upcoming",
      "time": 1518577200000,
      "updated": 1503534284000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "101 W. Broadway #1125",
        "city": "San Diego",
        "country": "us",
        "id": 25049077,
        "lat": 0,
        "localized_country_name": "USA",
        "lon": 0,
        "name": "Origin Code Academy",
        "repinned": false,
        "state": "CA",
        "zip": "",
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 12,
    },
    Object {
      "created": 1454528554000,
      "description": "<p>On the third Tuesday of every month we get together and work on javascript projects, learn from each other, and generally hang out. Bring your own project (BYOP), your questions, your ideas, and a six pack of your favorite beer.</p> <p>Please respect our Code of Conduct</p> <p>We welcome people of all backgrounds and skill levels. In keeping with the sandiego.js spirit, please be friendly, welcoming, and respectful.</p> <p>Please be respectful of others and respect our code of conduct (<a href=\"http://sandiegojs.org/code-of-conduct.html\" class=\"linkified\">http://sandiegojs.org/code-of-conduct.html</a>).</p> ",
      "duration": 7200000,
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "id": "sqrzplyxdbbc",
      "link": "https://www.meetup.com/sandiegojs/events/246924566/",
      "local_date": "2018-02-20",
      "local_time": "19:00",
      "name": "BYOP Night",
      "rsvp_limit": 50,
      "status": "upcoming",
      "time": 1519182000000,
      "updated": 1510103058000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "101 W. Broadway, Suite 1100",
        "city": "San Diego",
        "country": "us",
        "id": 24328721,
        "lat": 32.715118408203125,
        "localized_country_name": "USA",
        "lon": -117.16421508789062,
        "name": "Origin Code Academy",
        "repinned": false,
        "state": "CA",
        "zip": "",
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 5,
    },
    Object {
      "created": 1503531775000,
      "description": "<p>On the 4th Wednesday of every month, FundamentalJS meets to learn about one element or building block of Javascript. We talk about the concept and learn by doing on our laptops.</p> <p>We are open to everyone coming in, from beginners who are learning the language to established coders who want to brush up on a concept.</p> <p>PARKING</p> <p>Unfortunately we cannot help with parking. Horton Plaza is within two blocks and has one hour of parking for free, then charges $8 an hour.</p> <p>GETTING IN</p> <p>Walk up the to entrance of the building that faces the Horton Plaza mall. You may have to knock on the glass doors to be let in. Once you're in the lobby, ask the front desk attendant to be let up to the 11th floor for the Origin Code Academy meetup.</p> ",
      "duration": 7200000,
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "id": "pbzxqnyxdblc",
      "link": "https://www.meetup.com/sandiegojs/events/247087896/",
      "local_date": "2018-02-28",
      "local_time": "18:30",
      "name": "Fundamental JS",
      "rsvp_limit": 80,
      "status": "upcoming",
      "time": 1519871400000,
      "updated": 1503531775000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "101 W. Broadway #1100",
        "city": "San Diego, CA ",
        "country": "us",
        "id": 25263207,
        "lat": 32.71503829956055,
        "localized_country_name": "USA",
        "lon": -117.16419219970703,
        "name": "Origin Code Academy",
        "repinned": false,
        "state": "CA",
        "zip": "",
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 8,
    },
    Object {
      "created": 1499106128000,
      "description": "<p>Speakers:<br/>TBD</p> <p>San Diego JavaScript meets the first Tuesday of each month, at Zeeto Downtown. This event will take place in Zeeto's Questionable Exchange on the first floor. We typically have a series of short talks and then hang out and socialize.</p> <p>@ 7:30 pm you can park in any available Zeeto parking spots (see the map).</p> <p>Want to give a talk?</p> <p>We typically host four to six 5 minute lightning talks each month. We want to hear you speak and we're here to help you give a talk. Find out how to give a 5 minute talk at our next event. (<a href=\"http://sandiegojs.org/give-a-talk.html\" class=\"linkified\">http://sandiegojs.org/give-a-talk.html</a>)</p> <p>Please respect our Code of Conduct</p> <p>We welcome people of all backgrounds and skill levels. In keeping with the sandiego.js spirit, please be friendly, welcoming, and respectful.</p> <p>Please be respectful of others and respect our code of conduct (<a href=\"http://sandiegojs.org/code-of-conduct.html\" class=\"linkified\">http://sandiegojs.org/code-of-conduct.html</a>).</p> <p>Find us online</p> <p>Our website is sandiegojs.org (<a href=\"http://sandiegojs.org/\" class=\"linkified\">http://sandiegojs.org/</a>). Our IRC channel (<a href=\"http://sandiegojs.org/chat-room.html\" class=\"linkified\">http://sandiegojs.org/chat-room.html</a>) is #sandiegojs on FreeNode. We also have a Slack channel.</p> <p>Parking info</p> <p><img src=\"https://secure.meetupstatic.com/photos/event/3/d/3/3/600_444675667.jpeg\" /></p> ",
      "duration": 10800000,
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "id": "ktlwfpyxfbjb",
      "link": "https://www.meetup.com/sandiegojs/events/246671942/",
      "local_date": "2018-03-06",
      "local_time": "19:30",
      "name": "San Diego JS Monthly Meeting",
      "rsvp_limit": 150,
      "status": "upcoming",
      "time": 1520393400000,
      "updated": 1516139730000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "925 B St.",
        "city": "San Diego",
        "country": "us",
        "id": 24306491,
        "lat": 32.71753692626953,
        "localized_country_name": "USA",
        "lon": -117.1558837890625,
        "name": "Zeeto",
        "repinned": false,
        "state": "CA",
        "zip": "92101",
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 4,
    },
  ],
}
2:41:24 PM
props Object {
  "dispatch": [Function anonymous],
  "eventDetails": Array [
    Object {
      "created": 1456184674000,
      "description": "<p>Location: Booze Brothers. The tasting room has a great vibe. This is our quarterly SDJS hangout we host it at a local bar around SanDiego county. It's open to all community members, 21 and up. It's is an informal hangout so feel free to stop by, bring your laptop, have a cold beverage, and chat about problems or solutions you're dealing with using JavaScript.</p> <p>Please respect our Code of Conduct</p> <p>We welcome people of all backgrounds and skill levels. In keeping with the sandiego.js spirit, please be friendly, welcoming, and respectful.</p> <p>Please be respectful of others and respect our code of conduct (<a href=\"http://sandiegojs.org/code-of-conduct.html\" class=\"linkified\">http://sandiegojs.org/code-of-conduct.html</a>).</p> ",
      "duration": 7200000,
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "how_to_find_us": "Park on the street or in the lot to the east of Booze Brothers",
      "id": "fqgtqlyxcbrb",
      "link": "https://www.meetup.com/sandiegojs/events/246082820/",
      "local_date": "2018-01-27",
      "local_time": "16:00",
      "name": "SDJS Social Hour",
      "status": "upcoming",
      "time": 1517097600000,
      "updated": 1516075455000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "2545 Progress St Ste D",
        "city": "Vista",
        "country": "US",
        "id": 19364922,
        "lat": 33.14801025390625,
        "localized_country_name": "USA",
        "lon": -117.21770477294922,
        "name": "Booze Brothers",
        "repinned": false,
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 31,
    },
    Object {
      "created": 1499106128000,
      "description": "<p>Speakers:<br/>TBD</p> <p>San Diego JavaScript meets the first Tuesday of each month, at Zeeto Downtown. This event will take place in Zeeto's Questionable Exchange on the first floor. We typically have a series of short talks and then hang out and socialize.</p> <p>@ 7:30 pm you can park in any available Zeeto parking spots (see the map).</p> <p>Want to give a talk?</p> <p>We typically host four to six 5 minute lightning talks each month. We want to hear you speak and we're here to help you give a talk. Find out how to give a 5 minute talk at our next event. (<a href=\"http://sandiegojs.org/give-a-talk.html\" class=\"linkified\">http://sandiegojs.org/give-a-talk.html</a>)</p> <p>Please respect our Code of Conduct</p> <p>We welcome people of all backgrounds and skill levels. In keeping with the sandiego.js spirit, please be friendly, welcoming, and respectful.</p> <p>Please be respectful of others and respect our code of conduct (<a href=\"http://sandiegojs.org/code-of-conduct.html\" class=\"linkified\">http://sandiegojs.org/code-of-conduct.html</a>).</p> <p>Find us online</p> <p>Our website is sandiegojs.org (<a href=\"http://sandiegojs.org/\" class=\"linkified\">http://sandiegojs.org/</a>). Our IRC channel (<a href=\"http://sandiegojs.org/chat-room.html\" class=\"linkified\">http://sandiegojs.org/chat-room.html</a>) is #sandiegojs on FreeNode. We also have a Slack channel.</p> <p>Parking info</p> <p><img src=\"https://secure.meetupstatic.com/photos/event/3/d/3/3/600_444675667.jpeg\" /></p> ",
      "duration": 10800000,
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "id": "ktlwfpyxdbjb",
      "link": "https://www.meetup.com/sandiegojs/events/246651133/",
      "local_date": "2018-02-06",
      "local_time": "19:30",
      "name": "San Diego JS Monthly Meeting",
      "rsvp_limit": 150,
      "status": "upcoming",
      "time": 1517974200000,
      "updated": 1516139730000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "925 B St.",
        "city": "San Diego",
        "country": "us",
        "id": 24306491,
        "lat": 32.71753692626953,
        "localized_country_name": "USA",
        "lon": -117.1558837890625,
        "name": "Zeeto",
        "repinned": false,
        "state": "CA",
        "zip": "92101",
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 35,
    },
    Object {
      "created": 1503534284000,
      "description": "<p><b>Game Dev Night</b> runs <b>e</b><b>very 2nd Tuesday</b> of the month. We're here to talk shop about all Game Dev topics, especially those revolving around JS and HTML5 games. Normally we'll have a presentation or two, then you'll be able to collaborate and learn from each other.</p> <p>We're open to everyone coming in, beginners, seniors, artists, and developers. Anyone looking to make, work, and play games.</p> <p>


<b>PARKING</b></p> <p><br/>Unfortunately we cannot help with parking. Horton Plaza is within two blocks and has one hour of parking for free, then charges $8 an hour.</p> <p><b><br/></b></p> <p><b>GETTING IN</b></p> <p>Walk up the to entrance of the building that faces the Horton Plaza mall. You may have to knock on the glass doors to be let in. Once you're in the lobby, ask the front desk attendant to be let up to the 11th floor for the Origin Code Academy meetup.</p> <p><b><br/></b></p> <p><b>Please respect our Code of Conduct </b></p> <p>We welcome people of all backgrounds and skill levels.  In keeping with the sandiego.js spirit, please be friendly, welcoming, and respectful.</p> <p>Please be respectful of others and respect our <a href=\"http://sandiegojs.org/code-of-conduct.html\">code of conduct</a>.</p> ",
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "id": "dvzxqnyxdbrb",
      "link": "https://www.meetup.com/sandiegojs/events/246652798/",
      "local_date": "2018-02-13",
      "local_time": "19:00",
      "name": "Game Dev Night",
      "rsvp_limit": 100,
      "status": "upcoming",
      "time": 1518577200000,
      "updated": 1503534284000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "101 W. Broadway #1125",
        "city": "San Diego",
        "country": "us",
        "id": 25049077,
        "lat": 0,
        "localized_country_name": "USA",
        "lon": 0,
        "name": "Origin Code Academy",
        "repinned": false,
        "state": "CA",
        "zip": "",
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 12,
    },
    Object {
      "created": 1454528554000,
      "description": "<p>On the third Tuesday of every month we get together and work on javascript projects, learn from each other, and generally hang out. Bring your own project (BYOP), your questions, your ideas, and a six pack of your favorite beer.</p> <p>Please respect our Code of Conduct</p> <p>We welcome people of all backgrounds and skill levels. In keeping with the sandiego.js spirit, please be friendly, welcoming, and respectful.</p> <p>Please be respectful of others and respect our code of conduct (<a href=\"http://sandiegojs.org/code-of-conduct.html\" class=\"linkified\">http://sandiegojs.org/code-of-conduct.html</a>).</p> ",
      "duration": 7200000,
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "id": "sqrzplyxdbbc",
      "link": "https://www.meetup.com/sandiegojs/events/246924566/",
      "local_date": "2018-02-20",
      "local_time": "19:00",
      "name": "BYOP Night",
      "rsvp_limit": 50,
      "status": "upcoming",
      "time": 1519182000000,
      "updated": 1510103058000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "101 W. Broadway, Suite 1100",
        "city": "San Diego",
        "country": "us",
        "id": 24328721,
        "lat": 32.715118408203125,
        "localized_country_name": "USA",
        "lon": -117.16421508789062,
        "name": "Origin Code Academy",
        "repinned": false,
        "state": "CA",
        "zip": "",
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 5,
    },
    Object {
      "created": 1503531775000,
      "description": "<p>On the 4th Wednesday of every month, FundamentalJS meets to learn about one element or building block of Javascript. We talk about the concept and learn by doing on our laptops.</p> <p>We are open to everyone coming in, from beginners who are learning the language to established coders who want to brush up on a concept.</p> <p>PARKING</p> <p>Unfortunately we cannot help with parking. Horton Plaza is within two blocks and has one hour of parking for free, then charges $8 an hour.</p> <p>GETTING IN</p> <p>Walk up the to entrance of the building that faces the Horton Plaza mall. You may have to knock on the glass doors to be let in. Once you're in the lobby, ask the front desk attendant to be let up to the 11th floor for the Origin Code Academy meetup.</p> ",
      "duration": 7200000,
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "id": "pbzxqnyxdblc",
      "link": "https://www.meetup.com/sandiegojs/events/247087896/",
      "local_date": "2018-02-28",
      "local_time": "18:30",
      "name": "Fundamental JS",
      "rsvp_limit": 80,
      "status": "upcoming",
      "time": 1519871400000,
      "updated": 1503531775000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "101 W. Broadway #1100",
        "city": "San Diego, CA ",
        "country": "us",
        "id": 25263207,
        "lat": 32.71503829956055,
        "localized_country_name": "USA",
        "lon": -117.16419219970703,
        "name": "Origin Code Academy",
        "repinned": false,
        "state": "CA",
        "zip": "",
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 8,
    },
    Object {
      "created": 1499106128000,
      "description": "<p>Speakers:<br/>TBD</p> <p>San Diego JavaScript meets the first Tuesday of each month, at Zeeto Downtown. This event will take place in Zeeto's Questionable Exchange on the first floor. We typically have a series of short talks and then hang out and socialize.</p> <p>@ 7:30 pm you can park in any available Zeeto parking spots (see the map).</p> <p>Want to give a talk?</p> <p>We typically host four to six 5 minute lightning talks each month. We want to hear you speak and we're here to help you give a talk. Find out how to give a 5 minute talk at our next event. (<a href=\"http://sandiegojs.org/give-a-talk.html\" class=\"linkified\">http://sandiegojs.org/give-a-talk.html</a>)</p> <p>Please respect our Code of Conduct</p> <p>We welcome people of all backgrounds and skill levels. In keeping with the sandiego.js spirit, please be friendly, welcoming, and respectful.</p> <p>Please be respectful of others and respect our code of conduct (<a href=\"http://sandiegojs.org/code-of-conduct.html\" class=\"linkified\">http://sandiegojs.org/code-of-conduct.html</a>).</p> <p>Find us online</p> <p>Our website is sandiegojs.org (<a href=\"http://sandiegojs.org/\" class=\"linkified\">http://sandiegojs.org/</a>). Our IRC channel (<a href=\"http://sandiegojs.org/chat-room.html\" class=\"linkified\">http://sandiegojs.org/chat-room.html</a>) is #sandiegojs on FreeNode. We also have a Slack channel.</p> <p>Parking info</p> <p><img src=\"https://secure.meetupstatic.com/photos/event/3/d/3/3/600_444675667.jpeg\" /></p> ",
      "duration": 10800000,
      "group": Object {
        "created": 1310765404000,
        "id": 2180781,
        "join_mode": "open",
        "lat": 32.88999938964844,
        "localized_location": "San Diego, CA",
        "lon": -117.19999694824219,
        "name": "San Diego JavaScript Community",
        "region": "en_US",
        "urlname": "sandiegojs",
        "who": "JavaScripters",
      },
      "id": "ktlwfpyxfbjb",
      "link": "https://www.meetup.com/sandiegojs/events/246671942/",
      "local_date": "2018-03-06",
      "local_time": "19:30",
      "name": "San Diego JS Monthly Meeting",
      "rsvp_limit": 150,
      "status": "upcoming",
      "time": 1520393400000,
      "updated": 1516139730000,
      "utc_offset": -28800000,
      "venue": Object {
        "address_1": "925 B St.",
        "city": "San Diego",
        "country": "us",
        "id": 24306491,
        "lat": 32.71753692626953,
        "localized_country_name": "USA",
        "lon": -117.1558837890625,
        "name": "Zeeto",
        "repinned": false,
        "state": "CA",
        "zip": "92101",
      },
      "visibility": "public",
      "waitlist_count": 0,
      "yes_rsvp_count": 4,
    },
  ],
}